### ISSUE TITLE
UI: Change buttons from hide/show actions to tabs.

### ISSUE THREAD

**Issue by andreaspeters** [AVENTER-UG/docker-mesos-extension#3]
The icon-buttons in the extension shouldn’t behave as hide/show actions. Users want to navigate (switching between tabs) and not filter (hide/show behavior). Change the the icons to tabs (https://www.figma.com/file/U7pLWfEf6IQKUHLhdateBI/Docker-Extensions-UI-Styleguide?node-id=460:6168).

The following button would be affected:

- Home
- Show Tasks
- Show Frameworks
- Show Agents

**Comment by ghost** [comment]
Hi! Can I work on this issue?

**Comment by andreaspeters** [comment]
I would be happy. :-)

**Comment by Le-Roi777** [comment]
Hi guys hope all is well :-)
@andreaspeters may I also work on this?

**Comment by andreaspeters** [comment]
@VoidCupboard are u working on that? :-)

**Comment by ghost** [comment]
I am sorry @andreaspeters, I am unable to work on this issue since I am on an Arch-based distro and having issues using Docker Desktop (I have reported an issue in the repo). Let @Le-Roi777 work on this issue

**Comment by andreaspeters** [comment]
@VoidCupboard  I know your pain. Have also issues with docker-desktop under arch. I Have to copy the binary `com.docker.driver.amd64-linux` from docker-desktop 4.8.2 into the current version. Then it works. :-)

**Comment by Le-Roi777** [comment]
> I am sorry @andreaspeters, I am unable to work on this issue since I am on an Arch-based distro and having issues using Docker Desktop (I have reported an issue in the repo). Let @Le-Roi777 work on this issue

Awesome! Keep you posted :-)

**Comment by andreaspeters** [comment]
Thanks @Le-Roi777  for jump in. :-)

**Comment by ghost** [comment]
> @VoidCupboard  I know your pain. Have also issues with docker-desktop under arch. I Have to copy the binary `com.docker.driver.amd64-linux` from docker-desktop 4.8.2 into the current version. Then it works. :-) 

I do got my docker desktop running through the same way as you mentioned, but then I had the `extensions` command issue (it was not found). I removed docker and reinstalled docker desktop but then I got path issues

**Comment by Le-Roi777** [comment]
Hey guys :-)

Okay so at the moment we have the details expand icon next to the tabs. May I suggest that we make the details part of the tabs as well? It will simplify things a lot and also keep it clean and readable in the menu component.
![tabs](https://user-images.githubusercontent.com/56315245/194849192-3cd5a162-babf-4cf5-9395-7746ad9af9d3.png)

Or we could also have a single accordion item at the bottom of the tabs containing the details : -)

**Comment by andreaspeters** [comment]
@Le-Roi777 sounds interesting. I'm fine with that. :+1:

**Comment by andreaspeters** [comment]
@VoidCupboard 🤷‍♂️ Do u have matrix/element as chat? Would be easier to see if we can fix it together.
